// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launchd} from '../models';

export function BatchExecute(arg1:launchd.BatchExecuteRequest):Promise<launchd.BatchExecuteResponse>;

export function ClearServiceLogs(arg1:launchd.ClearServiceLogsRequest):Promise<launchd.ClearServiceLogsResponse>;

export function ExecuteServiceAction(arg1:launchd.ExecuteServiceActionRequest):Promise<launchd.ExecuteServiceActionResponse>;

export function GetServiceDetail(arg1:string):Promise<launchd.ServiceDetail>;

export function GetServiceEditor(arg1:string):Promise<launchd.ServiceEditorState>;

export function GetThemeMode():Promise<string>;

export function GetWorkspaceSnapshot():Promise<launchd.WorkspaceSnapshot>;

export function ListServiceHistory(arg1:string):Promise<Array<launchd.HistoryEntry>>;

export function ReadServiceLogs(arg1:launchd.ReadServiceLogsRequest):Promise<launchd.ReadServiceLogsResponse>;

export function SaveServiceConfig(arg1:launchd.SaveServiceConfigRequest):Promise<launchd.SaveServiceConfigResponse>;

export function SaveThemeMode(arg1:string):Promise<void>;

export function ValidateServiceConfig(arg1:launchd.ValidateServiceConfigRequest):Promise<launchd.ValidateServiceConfigResponse>;
