// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExecute(arg1) {
  return window['go']['main']['App']['BatchExecute'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearServiceLogs(arg1) {
  return window['go']['main']['App']['ClearServiceLogs'](arg1);
}

export function ExecuteServiceAction(arg1) {
  return window['go']['main']['App']['ExecuteServiceAction'](arg1);
}

export function GetServiceDetail(arg1) {
  return window['go']['main']['App']['GetServiceDetail'](arg1);
}

export function GetServiceEditor(arg1) {
  return window['go']['main']['App']['GetServiceEditor'](arg1);
}

export function GetThemeMode() {
  return window['go']['main']['App']['GetThemeMode']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function GetWorkspaceSnapshot() {
  return window['go']['main']['App']['GetWorkspaceSnapshot']();
}

export function InstallPreparedUpdate() {
  return window['go']['main']['App']['InstallPreparedUpdate']();
}

export function ListServiceHistory(arg1) {
  return window['go']['main']['App']['ListServiceHistory'](arg1);
}

export function PrepareUpdate() {
  return window['go']['main']['App']['PrepareUpdate']();
}

export function ReadServiceLogs(arg1) {
  return window['go']['main']['App']['ReadServiceLogs'](arg1);
}

export function SaveServiceConfig(arg1) {
  return window['go']['main']['App']['SaveServiceConfig'](arg1);
}

export function SaveThemeMode(arg1) {
  return window['go']['main']['App']['SaveThemeMode'](arg1);
}

export function ValidateServiceConfig(arg1) {
  return window['go']['main']['App']['ValidateServiceConfig'](arg1);
}
